### ISSUE TITLE
Task: Add an ElasticSearch microservice

### ISSUE THREAD

**Issue by ReinderVosDeWael** [cmi-dair/ctk-orchestrator#2]
### Description

We want to have the ability to save requests/responses to OpenAI, both for caching and auditing purposes. 

### Tasks

- [ ] Include an ElasticSearch microservice.
  - [ ] The ElasticSearch is only accessible by the API.
  - [ ] The ElasticSearch is secured with credentials passed to the API via environment variables. 
  - [ ] Modify the README to reflect the new architecture.
